<a href="https://colab.research.google.com/github/Saidmurodjon/data-science/blob/main/Chiziqli_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
x = np.array([[1., 2.,3.],[ 4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
y = np.array([[5., 5.,5.],[ 4., 4., 4.]])
y

array([[5., 5., 5.],
       [4., 4., 4.]])

In [6]:
x+y

array([[ 6.,  7.,  8.],
       [ 8.,  9., 10.]])

In [16]:
u=np.arange(30)
v=np.arange(30)
u-v


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
x*5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [20]:
x = np.array([[1., 2.,3.],[ 4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [22]:
y = np.array([[1., 2.],[ 4., 5.],[3.,5.]])
y

array([[1., 2.],
       [4., 5.],
       [3., 5.]])

In [26]:
x.dot(y)

array([[18., 27.],
       [42., 63.]])

In [28]:
np.dot(x,y)

array([[18., 27.],
       [42., 63.]])

In [30]:
y.dot(x)

array([[ 9., 12., 15.],
       [24., 33., 42.],
       [23., 31., 39.]])

In [ ]:
# Liner Algebra
from numpy.linalg import inv
