<a href="https://colab.research.google.com/github/Saidmurodjon/data-science/blob/main/Copy_of_Matemtik_va_statistik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [ ]:
arr = np.random.rand(5,4)
arr

array([[0.80385139, 0.82350486, 0.3996518 , 0.86944783],
       [0.76790143, 0.17105542, 0.68002086, 0.20276608],
       [0.42624315, 0.66286925, 0.19715983, 0.49318101],
       [0.80973968, 0.88008391, 0.42712516, 0.80482888],
       [0.39627217, 0.59638602, 0.46020581, 0.07574388]])

In [ ]:
arr.sum()

np.float64(10.948038435519486)

In [ ]:
np.sum(arr)

np.float64(10.948038435519486)

In [ ]:
arr.sum(axis=1) #qator yig'indisi

array([2.89645589, 1.8217438 , 1.77945323, 2.92177764, 1.52860788])

In [ ]:
arr.sum(axis=0) #qator yig'ndisi

array([3.20400783, 3.13389946, 2.16416347, 2.44596767])

In [ ]:
#sodda malumot
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [ ]:
mean = np.sum(data)/len(data)
mean

np.float64(2.0)

In [ ]:
np.mean(data)
mean

np.float64(2.0)

In [ ]:
np.mean(arr) #arrayning o'rtacha qiymati

np.float64(0.5474019217759742)

In [ ]:
np.mean(arr, axis=1) #qator bo'yicha o'rtacha ma'lumotlarni qaytaradi

array([0.72411397, 0.45543595, 0.44486331, 0.73044441, 0.38215197])

In [ ]:
np.mean(arr, axis=0) #qator bo'yicha o'rtacha ma'lumotlarni qaytaradi

array([0.64080157, 0.62677989, 0.43283269, 0.48919353])

In [ ]:
arr.mean(axis=0)  #qator bo'yicha o'rtacha ma'lumotlarni qaytaradi

array([0.64080157, 0.62677989, 0.43283269, 0.48919353])

In [ ]:
data

array([0, 1, 2, 3, 4])

In [ ]:
data.cumsum()

array([ 0,  1,  3,  6, 10])

In [ ]:
np.cumsum(data)

array([ 0,  1,  3,  6, 10])