<a href="https://colab.research.google.com/github/Saidmurodjon/data-science/blob/main/Sorting_tartiblash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
#data
arr =np.random.rand(4) # 4 ta taxminiy elementlardan tashkil topgan massiv
arr

array([0.15750018, 0.82052352, 0.20861399, 0.26757185])

In [11]:
  sorted_arr=np.sort(arr) # arr massivning tartiblangan ko'rinishini sorted_arr joylaydi
  sorted_arr

array([0.15750018, 0.20861399, 0.26757185, 0.82052352])

In [14]:
# 2-usul
arr.sort() #arr ning tartiblangan ko'rinishi
arr

array([0.15750018, 0.20861399, 0.26757185, 0.82052352])

In [17]:
# teskasi tartiblash
rev_arr = -np.sort(-arr) # teskari tartibdagi arr
rev_arr

array([0.82052352, 0.26757185, 0.20861399, 0.15750018])

In [20]:
# 2 D array (massiv)
arr2d=np.random.rand(2,4)
arr2d

array([[0.43319595, 0.14465261, 0.71005999, 0.48895492],
       [0.41524447, 0.67307449, 0.77417269, 0.01810886]])

In [24]:

# axis=0 --> qator
row_srt=np.sort(arr2d,axis=0) # arr2d ning har bir qator bo'yicha tartiblangan ko'rinishi
row_srt

array([[0.41524447, 0.14465261, 0.71005999, 0.01810886],
       [0.43319595, 0.67307449, 0.77417269, 0.48895492]])

In [26]:
# axis=1 --> Ustun
col_srt=np.sort(arr2d,axis=1) # arr2d ning har bir ustun bo'yicha tartiblangan ko'rinishi
col_srt

array([[0.14465261, 0.43319595, 0.48895492, 0.71005999],
       [0.01810886, 0.41524447, 0.67307449, 0.77417269]])