<a href="https://colab.research.google.com/github/Saidmurodjon/data-science/blob/main/Visualizatsiya%20amaliyot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/h4PPC71.png)
#Data Sayns va Sunʼiy Intellekt Praktikum

#8.26. NumPy kutubxonasi boʻyicha amaliy vazifa

Topshiriqni aynan qanday funksiyalar yordamida bajarish mumkinligi `💡Ishora` koʻrinishida berilgan.

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va uni chop eting.

Versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [56]:
import numpy as np
np.version

<module 'numpy.version' from '/usr/local/lib/python3.12/dist-packages/numpy/version.py'>

#### 2. Raqamli qiymatlar roʻyxatini bir oʻlchovli NumPy massiviga aylantiring.

`💡Ishora` numpy.array

In [57]:
massiv = np.array([1, 2, 3, 4, 5])
massiv

array([1, 2, 3, 4, 5])

#### 3. Qiymatlari noldan iborat boʻlgan toʻqqiz elementdan iborat massiv yarating.


---




`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [58]:
v=massiv.size*massiv.itemsize
v

40

#### 5. NumPy kutubxonasidagi `add` funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [59]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Shunday vekor yaratingki u oʻn ikki oʻlchamda va qiymatlari noldan iborat boʻlsin, lekin vektorning oltinchi qiymati 1 ga teng boʻlsin.



`💡Ishora` array[12]

In [60]:
v = np.zeros(12, dtype=int)  # 12 ta nol
v[5] = 1                     # oltinchi elementni 1 qilish
v

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

#### 7. Qiymatlari 20 dan 59 gacha boʻlgan vektor yarating.



`💡Ishora` arange

In [61]:
v = np.arange(20, 60)   # 20 dan 59 gacha
v

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari oʻzgartiring, (birinchi element oxirgisi boʻlsin)



`💡Ishora` array[::-1]

In [62]:
v = np.array([1, 2, 3, 4, 5])
teskari = v[::-1]
teskari

array([5, 4, 3, 2, 1])

#### 9. 12 dan 20 gacha boʻlgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [63]:
m = np.arange(12, 21).reshape(3, 3)
m

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng boʻlmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [64]:
a = np.array([3, 7, 0, 0, 9, 0])
indekslar = np.nonzero(a)
indekslar

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 oʻlchovidagi massiv yarating.


`💡Ishora` np.random.random

In [65]:
arr = np.random.random((2,2,2))
arr

array([[[0.21570085, 0.45583624],
        [0.4495821 , 0.91314893]],

       [[0.01876082, 0.62283032],
        [0.10590594, 0.57265861]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 oʻlchamidagi massiv yarating. Soʻng uning eng katta va eng kichik qiymatlarini toping.


`💡Ishora` min, max

In [66]:
m = np.random.random((9, 9))

# Eng kichik va eng katta qiymatlar
print("Massiv:\n", m)
print("Eng kichik qiymat:", m.min())
print("Eng katta qiymat:", m.max())

Massiv:
 [[0.65256884 0.32755861 0.04575346 0.99255823 0.44406945 0.13549227
  0.08774703 0.07877875 0.73043633]
 [0.35854686 0.96696207 0.61138034 0.38047255 0.97625375 0.11271188
  0.35751315 0.08848102 0.31947004]
 [0.17497022 0.38376377 0.05484548 0.51141307 0.63716645 0.64516789
  0.24945849 0.19707325 0.07098228]
 [0.30634102 0.07919264 0.23165574 0.99214521 0.53681452 0.23318062
  0.71296624 0.19966067 0.63633754]
 [0.35497276 0.54904266 0.54077428 0.07492767 0.39047814 0.44524467
  0.88052129 0.78881499 0.11480776]
 [0.64687859 0.00890007 0.05198425 0.92788272 0.7783014  0.29056495
  0.37677738 0.81318899 0.32750566]
 [0.76450923 0.31181554 0.4985423  0.70146217 0.68116725 0.18266403
  0.95403758 0.83522732 0.16785136]
 [0.84179557 0.60707176 0.54646469 0.04310294 0.99915869 0.92020742
  0.11140785 0.08177464 0.3550203 ]
 [0.1419776  0.12152317 0.94674183 0.01637912 0.79548015 0.04806532
  0.45849546 0.39729447 0.9892124 ]]
Eng kichik qiymat: 0.00890006914684327
Eng katta qiyma

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [67]:
0 * np.nan
#NaN bilan amal bajarilsa, natija ham NaN bo'ladi.
np.nan == np.nan
#NaN hech qachon NaN ga teng emas.

np.inf > np.nan
#NaN bilan solishtirilganda natija doim False.

np.nan - np.nan
#NaN ustida amal → NaN).

np.nan in set([np.nan])
#set ichida NaN mavjud, shuning uchun True.

0.7 == 7 * 0.1
#floating-point aniqlik muammosi tufayli 0.7 ≠ 0.7000000000000001.

False

#### 14. Oʻlchamlari 6x3 va 3x4 boʻlgan martitsa yarating, soʻng ularning  koʻpaytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [68]:
A = np.ones((6, 3))
B = np.ones((3, 4))

C = np.dot(A, B)    # matritsalar ko'paytmasi
C

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [69]:
print(sum(range(5), -1)) #9

from numpy import *
print(sum(range(5), -1)) #10

10
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [70]:
a = np.array([1, 2])
b = np.array([4, 5])

print("a > b:", a > b)
print("a >= b:", a >= b)
print("a < b:", a < b)
print("a <= b:", a <= b)

a > b: [False False]
a >= b: [False False]
a < b: [ True  True]
a <= b: [ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [71]:
np.array(0) / np.array(0) #nan
np.array(0) // np.array(0) #nan
np.array([np.nan]).astype(int).astype(float) #-9.22337204e+18

/tmp/ipython-input-1108561014.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0) #nan
/tmp/ipython-input-1108561014.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0) #nan
/tmp/ipython-input-1108561014.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float) #-9.22337204e+18


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping.


`💡Ishora` np.intersect1d

In [72]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])

umumiy = np.intersect1d(a, b)
umumiy

array([4, 5])

#### 19. Tasodifiy sonlardan iborat boʻlgan massiv yarating, soʻng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [73]:
a = np.random.uniform(0, 10, 5)
# 1-usul: np.floor()  -> pastga qarab butun qism
print("np.floor:", np.floor(a))

# 2-usul: astype(int) -> butun turga o'tkazish
print("astype(int):", a.astype(int))

# 3-usul: np.trunc() -> kasr qismini kesib tashlash
print("np.trunc:", np.trunc(a))

# 4-usul: % operatori bilan kasr qismini olib tashlash
print("butun qism (%):", a - (a % 1))

np.floor: [3. 2. 9. 4. 1.]
astype(int): [3 2 9 4 1]
np.trunc: [3. 2. 9. 4. 1.]
butun qism (%): [3. 2. 9. 4. 1.]


#### 20. Oʻlchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha boʻlsin.



`💡Ishora` np.arange

In [74]:
matritsa = np.arange(0, 9).reshape(3, 3) % 3
print(matritsa)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


#### 21. Oʻchamlari 10 boʻlgan tasodifiy vektor yarating va uni oʻsish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [75]:
# 10 ta tasodifiy sonli vektor
v = np.random.randint(0, 100, 10)   # 0 dan 99 gacha butun sonlar
print("Asl vektor:", v)

# O'sish tartibida saralash
v_sorted = np.sort(v)
print("Saralangan vektor:", v_sorted)

Asl vektor: [49 81 86 98  3 15 43 48 13 95]
Saralangan vektor: [ 3 13 15 43 48 49 81 86 95 98]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

In [76]:
# Tasodifiy 5 elementli massivlar
A = np.random.randint(0, 10, 5)
B = np.random.randint(0, 10, 5)

print("Massiv A:", A)
print("Massiv B:", B)

# Tenglikni tekshirish
print("array_equal:", np.array_equal(A, B))   # aniq tenglik
print("allclose:", np.allclose(A, B))         # yaqin qiymatlar uchun

Massiv A: [3 4 9 2 6]
Massiv B: [0 5 2 9 0]
array_equal: False
allclose: False


#### 23. Oʻlchamlari 6x3 va 3x4 matritsa tuzing va ularni oʻzaro koʻpaytiring.


`💡Ishora` np.dot or np.ones

In [77]:
# 6x3 va 3x4 o'lchamdagi matritsalar
A = np.ones((6, 3))
B = np.ones((3, 4))

# Ko'paytirish
C = np.dot(A, B)

print("A:\n", A)
print("B:\n", B)
print("Natija (6x4):\n", C)

A:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
B:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Natija (6x4):
 [[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 24. Tasodifiy sonlardan iborat boʻlgan oʻlchami 5 ga teng vektor yarating, soʻng uning eng katta qiymatini 0 ga oʻzgartiring.


`💡Ishora` argmax

In [78]:
# Tasodifiy 5 elementli vektor
v = np.random.randint(0, 100, 5)
print("Asl vektor:", v)

# Eng katta elementning indeksini topish
idx = np.argmax(v)

# Uni 0 ga o'zgartirish
v[idx] = 0
print("O'zgartirilgan vektor:", v)

Asl vektor: [60 50 71 54 19]
O'zgartirilgan vektor: [60 50  0 54 19]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [79]:
# Bugungi sana
bugun = np.datetime64('today')

# Kecha va ertangi kun
kecha = bugun - np.timedelta64(1, 'D')
ertaga = bugun + np.timedelta64(1, 'D')

print("Kecha:", kecha)
print("Bugun:", bugun)
print("Ertaga:", ertaga)

Kecha: 2025-09-29
Bugun: 2025-09-30
Ertaga: 2025-10-01


#### 26. 2016 yil yanvar oyiga toʻgʻri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [80]:
# 2016 yil yanvar oyidagi barcha sanalar
sana = np.arange('2016-01', '2016-02', dtype='datetime64[D]')
sana

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [81]:
# Tasodifiy massiv (musbat sonlar)
a = np.random.uniform(1, 10, 5)   # 1 dan 10 gacha 5 ta son
print("Asl massiv:", a)

# 1-usul: floor (pastga qarab yaxlitlash)
print("np.floor:", np.floor(a))

# 2-usul: astype(int) (to'g'ridan-to'g'ri butun songa o'tkazish)
print("astype(int):", a.astype(int))

# 3-usul: trunc (butun qismini olish)
print("np.trunc:", np.trunc(a))

# 4-usul: % yordamida (qoldiqni olib tashlab butunni olish)
print("Butun qism (%):", a - a % 1)

Asl massiv: [1.97009097 7.50234092 7.79705781 6.1901218  7.2664668 ]
np.floor: [1. 7. 7. 6. 7.]
astype(int): [1 7 7 6 7]
np.trunc: [1. 7. 7. 6. 7.]
Butun qism (%): [1. 7. 7. 6. 7.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yigʻindisini `np.sum` funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [82]:
# Ixtiyoriy kichik massiv yaratamiz
a = np.array([2, 4, 6, 8, 10])

# np.sum() yordamida
print("np.sum:", np.sum(a))

# np.add.reduce() yordamida (tezroq ishlaydi)
print("np.add.reduce:", np.add.reduce(a))

np.sum: 30
np.add.reduce: 30


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [83]:
# Boshlang'ich vektor
a = np.array([1, 2, 3, 4, 5])

# Har bir element orasiga 3 ta nol qo'shish
b = np.zeros(len(a) * 4 - 3, dtype=int)  # uzunligi: elementlar + 3 ta nol
b[::4] = a
b

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

#### 30. Quyidagi `a` massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda `b` massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

`💡Ishora` stride_tricks.as_strided

In [84]:
from numpy.lib.stride_tricks import as_strided

# Asl massiv
a = np.arange(1, 15)

# Parametrlar
n = 4  # oynaning uzunligi
stride = a.strides[0]

# Sirpanma oynali massiv
b = as_strided(a, shape=(len(a) - n + 1, n), strides=(stride, stride))

b

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga oʻxshash qiymatlar kiriting. Soʻng, oʻxshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [85]:
# Tasodifiy massiv yaratamiz (o'xshash qiymatlar ham bo'ladi)
a = np.random.randint(0, 10, 20)  # 0 dan 9 gacha, uzunligi 20
print("Massiv:", a)

# Har bir qiymat necha marta qatnashganini sanash
counts = np.bincount(a)

# Eng ko'p uchragan qiymatni topish
most_common = np.argmax(counts)

print("O'xshash qiymatlar soni:", counts)
print("Eng ko'p uchragan qiymat:", most_common)

Massiv: [2 5 9 8 9 1 9 7 9 2 3 7 1 1 4 0 2 2 6 8]
O'xshash qiymatlar soni: [1 3 4 1 1 1 1 2 2 4]
Eng ko'p uchragan qiymat: 2


[link text](https://)#### BONUS topshiriq

`💡Oʻzingiz javob berishni istagan savolni kiriting va unga javob bering.`

In [86]:
# 0 dan 50 gacha bo'lgan 10 ta tasodifiy butun son
a = np.random.randint(0, 50, 10)
print("Massiv:", a)

# Juft sonlarni ajratib olish
juftlar = a[a % 2 == 0]
print("Juft sonlar:", juftlar)

# Toq sonlarni ajratib olish
toq_sonlar = a[a % 2 == 1]
print("Toq sonlar:", toq_sonlar)

Massiv: [18 20 19 37 21 11 40 16 25 21]
Juft sonlar: [18 20 40 16]
Toq sonlar: [19 37 21 11 25 21]
